[project]
name = "docubridge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fpdf>=1.7.2",
    "jsonschema>=4.23.0",
    "pdfplumber>=0.11.4",
    "pytest>=8.3.3",
    "reportlab>=4.2.5",
    "structlog>=24.4.0",
]
